"""Provider deadlines and the coordination windows that contain them."""

DEFAULT_RESPONSE_TIMEOUT_SECONDS = 240
MIN_RESPONSE_TIMEOUT_SECONDS = 10
MAX_RESPONSE_TIMEOUT_SECONDS = 600
AI_LOCK_LEASE_SECONDS = MAX_RESPONSE_TIMEOUT_SECONDS + 60
AI_OPERATION_STALE_SECONDS = AI_LOCK_LEASE_SECONDS + 60
